# Generated by Django 5.1 on 2024-09-11 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0003_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='oz',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
