# Generated by Django 5.1.1 on 2024-10-27 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0003_userprofile_email_alter_userprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
