# Generated by Django 5.1.1 on 2024-10-31 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
    ]
